# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_mocha"
add_newline = true
command_timeout = 2000

[aws]
symbol = "ó°¸ "
expiration_symbol = "ó°¯†"

[azure]
symbol = "ó° … "

[battery]
full_symbol = "ó°¹ "
empty_symbol = "ó°‚ "
unknown_symbol = "ó°¾ "
charging_symbol = "ó°‚„ "
discharging_symbol = "ó°‚ƒ "

[buf]
symbol = "ï’ "

[bun]
symbol = "îŠ "

[c]
symbol = "î˜ "

[character]
success_symbol = "[â¯](green)"
error_symbol = "[â¯](red)"
vimcmd_symbol = "[â®](green)"
vimcmd_replace_one_symbol = "[â®](bold purple)"
vimcmd_replace_symbol = "[â®](bold purple)"
vimcmd_visual_symbol = "[â®](bold yellow)"

[cmd_duration]
disabled = true

[cmake]
symbol = "â–³ "

[cobol]
symbol = "ï€“ "

[conda]
symbol = "ï„Œ "

[container]
symbol = "ó±£˜"

[crystal]
symbol = "ó°¬¯ "

[daml]
symbol = "Î› "

[dart]
symbol = "î˜ "

[deno]
symbol = "ğŸ¦• "

[directory]
home_symbol = "~"
read_only = " ó°Œ¾"
truncation_symbol = ""

[docker_context]
symbol = "ïŒˆ "

[dotnet]
symbol = "î¿ "
format = "via [$symbol($version )(ó°“¾ $tfm )]($style)"

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[erlang]
symbol = "î± "

[fennel]
symbol = "ğŸ§… "

[fill]
symbol = "."

[fossil_branch]
symbol = "ï˜ "
truncation_symbol = "â€¦"

[gcloud]
disabled = true
symbol = "ó°…Ÿ  "

[git_branch]
symbol = "ï˜ "
truncation_symbol = "â€¦"

[git_commit]
tag_symbol = " ó°Œ–  "

[git_status]
conflicted = "ó°‚­"
ahead = "ó°${count}"
behind = "ó°…${count}"
diverged = "ó°${ahead_count}ó°…${behind_count}"
up_to_date = ""
untracked = "?"
stashed = "ó±Š–"
modified = "ó°‡‚"
staged = "ó°•"
renamed = "ó°„¾"
deleted = "ó°…–"
typechanged = ""

[golang]
symbol = "î˜§ "

[gradle]
symbol = "î™  "

[guix_shell]
symbol = "ïŒ¥ "

[haskell]
symbol = "î· "

[haxe]
symbol = "î™¦ "

[helm]
symbol = "âˆ "

[hg_branch]
disabled = false
symbol = "ï˜ "
truncation_symbol = "â€¦"

[hostname]
ssh_symbol = "î¬ "

[java]
symbol = "î‰– "

[jobs]
symbol_threshold = 1
symbol = "âœ¦"

[julia]
symbol = "î˜¤ "

[kotlin]
symbol = "î˜´ "

[kubernetes]
symbol = "ó±ƒ¾ "

[lua]
symbol = "î˜  "

[memory_usage]
symbol = "ó°› "

[meson]
symbol = "ó°”· "
truncation_symbol = "â€¦"

[nim]
symbol = "ó°†¥ "

[nix_shell]
symbol = "ïŒ“ "

[nodejs]
symbol = "îœ˜ "

[ocaml]
symbol = "î™º "

[opa]
symbol = "ğŸª–  "

[openstack]
symbol = "ó°…Ÿ  "

[os]
disabled = false

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "[ïŒƒ ](blue)"
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "[ïŒ“ ](blue)"
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "[ïŒ› ](peach)"
Unknown = "ïˆ­ "
Windows = "[ó°² ](white)"

[package]
symbol = "ó°— "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[perl]
symbol = "î™¾ "

[php]
symbol = "î˜ˆ "

[pijul_channel]
symbol = "ï˜ "
truncation_symbol = "â€¦"

[pulumi]
symbol = "ï†² "

[purescript]
symbol = "î˜° "

[python]
symbol = "îˆµ "

[raku]
symbol = "îŠ "

[red]
symbol = "[ó°”¶](red) "

[rlang]
symbol = "ó°Ÿ” "

[ruby]
symbol = "î‘ "

[rust]
symbol = "î¨ "

[scala]
symbol = "îœ· "

[shell]
bash_indicator = "bsh"
cmd_indicator = "cmd"
disabled = true
elvish_indicator = "esh"
fish_indicator = "fsh"
ion_indicator = "ion"
nu_indicator = "nu"
powershell_indicator = "psh"
tcsh_indicator = "tsh"
unknown_indicator = ""
xonsh_indicator = "xsh"
zsh_indicator = "zsh"

[shlvl]
symbol = "ó°¹¹  "

[singularity]
symbol = ""

[solidity]
symbol = "S "

[spack]
symbol = "ğŸ…¢ "

[status]
map_symbol = false
symbol = "[ó°…–](red)"
success_symbol = ""
not_executable_symbol = "ó±ƒ“"
not_found_symbol = "ó°‰"
sigint_symbol = "ó°Ÿ¾"
signal_symbol = "ó±‹"

[sudo]
symbol = "ó±…§ "

[swift]
symbol = "î• "

[terraform]
symbol = "îšš "

[vagrant]
symbol = "â± "

[vcsh]
symbol = ""

[vlang]
symbol = "îš¬ "

[zig]
symbol = "îš© "
