# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_mocha"
add_newline = true
command_timeout = 2000

[aws]
symbol = "  "
expiration_symbol = "󰯆"

[azure]
symbol = " "

[battery]
full_symbol = "󰁹 "
empty_symbol = "󰂎 "
unknown_symbol = "󰁾 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"
vimcmd_replace_one_symbol = "[❮](bold purple)"
vimcmd_replace_symbol = "[❮](bold purple)"
vimcmd_visual_symbol = "[❮](bold yellow)"

[cmd_duration]
disabled = true

[cmake]
symbol = " "

[cobol]
symbol = " "

[conda]
symbol = " "

[container]
symbol = ""

[cpp]
symbol = " "

[crystal]
symbol = " "

[daml]
symbol = "Λ "

[dart]
symbol = " "

[deno]
symbol = " "

[directory]
home_symbol = "~"
read_only = " 󰌾"
truncation_symbol = ""

[direnv]
symbol = "direnv "

[docker_context]
symbol = " "

[dotnet]
symbol = " "
format = "via [$symbol($version )(󰓾 $tfm )]($style)"

[elixir]
symbol = " "

[elm]
symbol = " "

[erlang]
symbol = " "

[fennel]
symbol = " "

[fill]
symbol = "."

[fossil_branch]
symbol = " "
truncation_symbol = "…"

[gcloud]
disabled = true
symbol = "  "

[git_branch]
symbol = " "
truncation_symbol = "…"

[git_commit]
tag_symbol = " 󰌖  "

[git_metrics]

[git_state]

[git_status]
conflicted = "󰂭"
ahead = "󰁝${count}"
behind = "󰁅${count}"
diverged = "󰁝${ahead_count}󰁅${behind_count}"
up_to_date = ""
untracked = "?"
stashed = "󱊖"
modified = "󰇂"
staged = "󰐕"
renamed = "󰄾"
deleted = "󰅖"
typechanged = ""

[gleam]
symbol = " "

[golang]
symbol = " "

[gradle]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[helm]
symbol = " "

[hg_branch]
disabled = false
symbol = " "
truncation_symbol = "…"

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[jobs]
symbol_threshold = 1
symbol = "✦"

[julia]
symbol = " "

[kotlin]
symbol = " "

[kubernetes]
disabled = true
detect_folders = ["clusters"]
symbol = " "

[line_break]
disabled = false

[localip]
disabled = false
ssh_only = true

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "
truncation_symbol = "…"

[mise]
symbol = "mise "

[mojo]
symbol = "󰈸 "

[nats]
symbol = " "

[netns]
symbol = ""

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[odin]
symbol = "Ø "

[opa]
symbol = "󱢙  "

[openstack]
symbol = "  "

[os]
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = "[ ](blue)"
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = "[ ](blue)"
OpenBSD = "󰈺 "
OpenCloudOS = " "
openEuler = " "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = "[ ](peach)"
Ultramarine = "  "
Unknown = " "
Void = " "
Windows = "[󰍲 ](white)"

[package]
symbol = "󰏗 "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "
truncation_symbol = "…"

[pixi]
symbol = " "

[pulumi]
symbol = " "

[purescript]
symbol = " "

[python]
symbol = " "

[quarto]
symbol = "⨁ "

[raku]
symbol = " "

[red]
symbol = "[󰔶 ](red)"

[rlang]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shell]
disabled = true
bash_indicator = "bsh"
cmd_indicator = "cmd"
elvish_indicator = "esh"
fish_indicator = "fsh"
ion_indicator = "ion"
nu_indicator = "nu"
powershell_indicator = "psh"
tcsh_indicator = "tsh"
unknown_indicator = ""
xonsh_indicator = "xsh"
zsh_indicator = "zsh"

[shlvl]
symbol = "󰹹  "

[singularity]
symbol = ""

[solidity]
symbol = " "

[spack]
symbol = " "

[status]
map_symbol = false
symbol = "[󰅖](red)"
success_symbol = ""
not_executable_symbol = "󱃓"
not_found_symbol = "󰍉"
sigint_symbol = "󰟾"
signal_symbol = "󱐋"

[sudo]
symbol = "󱅧 "

[swift]
symbol = " "

[terraform]
symbol = " "

[time]
disabled = true

[typst]
symbol = "󰰤 "

[username]

[vagrant]
symbol = " "

[vcsh]
symbol = ""

[vlang]
symbol = " "

[zig]
symbol = " "
