[settings]
# Plugins can read the versions files used by other version managers (if enabled by the plugin)
# for example, .nvmrc in the case of node's nvm
legacy_version_file = true # Enabled by default (different than asdf)

# Configure `rtx install` to always keep the downloaded archive
always_keep_download = false # deleted after install by default
always_keep_install = false  # deleted on failure by default

# Configure how frequently (in minutes) to fetch updated plugin repository changes
# this is updated whenever a new runtime is installed
# (note: this isn't currently implemented but there are plans to add it: https://github.com/jdxcode/rtx/issues/128)
plugin_autoupdate_last_check_duration = '1 week' # set to 0 to disable updates

# Config files with these prefixes will be trusted by default
# trusted_config_paths = ['~/work/my-trusted-projects']

verbose = false     # set to true to see full installation output, see `RTX_VERBOSE`
asdf_compat = false # set to true to ensure .tool-versions will be compatible with asdf, see `RTX_ASDF_COMPAT`
jobs = 4            # Number of plugins or runtimes to install in parallel. The default is `4`.
raw = false         # set to true to directly pipe plugins to stdin/stdout/stderr

shorthands_file = '~/.config/mise/shorthands.toml' # path to the shorthands file, see `RTX_SHORTHANDS_FILE`
disable_default_shorthands = false                 # disable the default shorthands, see `RTX_DISABLE_DEFAULT_SHORTHANDS`
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]
# log_level = 'debug' # log verbosity, see `RTX_LOG_LEVEL`

[env]
MISE_NODE_COREPACK = { required = true }


[tools]
bun = "latest"
coder = "2.24.2"
deno = "latest"
k9s = "latest"
node = "lts"
npm = "latest"
pnpm = "latest"
